apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ml-platform-clearml-agent
    newName: registry.example.com/ml-platform/clearml-agent
    newTag: prod
patches:
  - path: patch.yaml
