apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-platform-clearml-worker
spec:
  template:
    spec:
      containers:
        - name: clearml-agent
          env:
            - name: CLEARML_AGENT_QUEUE
              value: cpu
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-platform-clearml-outputs
spec:
  resources:
    requests:
      storage: 100Gi
