apiVersion: v1
kind: Secret
metadata:
  name: clearml-credentials
type: Opaque
stringData:
  CLEARML_API_ACCESS_KEY: replace-me
  CLEARML_API_SECRET_KEY: replace-me
  CLEARML_API_HOST: https://api.example.com
  CLEARML_WEB_HOST: https://app.example.com
  CLEARML_FILES_HOST: https://files.example.com
