apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-platform-clearml-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-platform-clearml-worker
  template:
    metadata:
      labels:
        app: ml-platform-clearml-worker
    spec:
      containers:
        - name: clearml-agent
          image: ml-platform-clearml-agent:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CLEARML_AGENT_QUEUE
              value: default
          envFrom:
            - secretRef:
                name: clearml-credentials
          volumeMounts:
            - name: outputs
              mountPath: /mnt/clearml/outputs
      volumes:
        - name: outputs
          persistentVolumeClaim:
            claimName: ml-platform-clearml-outputs
