task: tabular_1d_output

run:
  name: tabular_1d_output

data:
  local_path: data/sample_train.csv
  clearml_dataset_id: null
  dataset_file: null
  x_column: x1
  value_column: target
  id_columns: [id]

output:
  table_name: tabular_1d_output.csv
