from __future__ import annotations

from pathlib import Path

from ml_platform_core.result import RunResult

from .reporting_scalars import report_artifact_scalars, report_result_metrics, report_table_scalars
from .reporting_targets import should_report_table, table_series


def _report_table(adapter, name: str, path: str | Path) -> None:
    adapter.report_table("tables", table_series(name), path, iteration=0)


def _report_plot_image(adapter, name: str, path: str | Path) -> None:
    report_image = getattr(adapter, "report_image", None)
    if callable(report_image):
        report_image("plots", name, path, iteration=0)
        return
    report_media = getattr(adapter, "report_media", None)
    if callable(report_media):
        report_media("plots", name, path, iteration=0)


def report_result(adapter, result: RunResult, *, upload_plots: bool = True) -> None:
    """Report RunResult to ClearML.

    Keep this small: upload artifacts/tables, publish scalar metrics, and
    report plot artifacts that were generated by the domain package.
    """
    report_result_metrics(adapter, result.metrics)
    _report_artifacts(adapter, result.artifacts)
    _report_tables(adapter, result.tables)
    _upload_plots(adapter, result.plots, upload_plots=upload_plots)


def _report_artifacts(adapter, artifacts: dict[str, Path]) -> None:
    for name, path in artifacts.items():
        adapter.upload_artifact(name, path)
        report_artifact_scalars(adapter, name, path)


def _report_tables(adapter, tables: dict[str, Path]) -> None:
    for name, path in tables.items():
        adapter.upload_artifact(name, path)
        if should_report_table(name):
            _report_table(adapter, name, path)
        report_table_scalars(adapter, name, path)


def _upload_plots(adapter, plots: dict[str, Path], *, upload_plots: bool) -> None:
    for name, path in plots.items():
        adapter.upload_artifact(name, path)
        if upload_plots:
            _report_plot_image(adapter, name, path)
